config/routes.rb
Rails.application.routes.draw do

devise_for :users
devise_scope :user do
	root :to => 'devise/sessions#new'
end

get 'images/control' => 'images#control', as: :images_control
get 'images/export' => 'images#export', as: :images_export
post 'images/import' => 'images#import', as: :images_import
get 'users' => 'users#users_admin', as: :users
put 'users/:id/approved' => 'users#approved', as: :approved
put 'users/:id/disapproved' => 'users#disapproved', as: :disapproved
put 'users/:id/approver' => 'users#approver', as: :approver
put 'users/:id/disapprover' => 'users#disapprover', as: :disapprover
put 'users/:id/set_admin' => 'users#set_admin', as: :set_admin
put 'users/:id/unset_admin' => 'users#unset_admin', as: :unset_admin
put 'users/public' => 'users#public', as: :public
put 'users/private' => 'users#private', as: :private
resources :users, only: [:show, :edit, :update, :destroy]

resources :categories, only: [:index, :new, :create] do
	post :search, on: :member
	resources :images do
		get :download, on: :member
	end
end
resources :categories, path: "", except: [:index, :new, :create]



  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	:recoverable, :rememberable, :trackable, :validatable
	validates :name, presence: true
	validates :company, presence: true
	validates :area, presence: true
	# validates :address, presence: true
	validates :phone, presence: true
	validates :cnpj, presence: true
	validates :work, presence: true
	validates :profile, presence: true

	after_create :send_admin_mail

	scope :admin, -> {where(admin: true).order("updated_at DESC") }
	scope :approved, -> { where(approved: true).order("updated_at DESC") }
	scope :disapproved, -> { where(approved: false).order("updated_at DESC") }
	scope :approver, -> { where(approver: true).order("updated_at DESC") }
		
	STABLE = ["guilhermebav@gmail.com"]


	def send_admin_mail
		AdminMailer.new_user_waiting_for_approval.deliver
	end

	def active_for_authentication?
		super && approved?
	end

	def inactive_message
		if !approved?
			:not_approved
		else
			super # Use whatever other message
		end
	end

	def self.send_reset_password_instructions(attributes={})
		recoverable = find_or_initialize_with_errors(reset_password_keys, attributes, :not_found)
		if !recoverable.approved?
			recoverable.errors[:base] << I18n.t("devise.failure.not_approved")
		elsif recoverable.persisted?
			recoverable.send_reset_password_instructions
		end
		recoverable
	end

	def self.to_csv(options = {})
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |product|
				csv << product.attributes.values_at(*column_names)
			end
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :set_user, only: [:show, :edit, :update, :destroy, :approved,
		 :disapproved, :approver, :disapprover, :set_admin, :unset_admin]
	before_action :is_admin?

	def users_admin
		if params[:approved] == "false"
			@users = User.disapproved.order("updated_at DESC")
			@title = "esperando aprovação"
		elsif params[:admin] == "true"
			@users = User.admin
			@title = "administradores"
		else
			@users = User.all.order("updated_at DESC")
			@title = "todos"
		end
		respond_to do |format|
			format.html { render "users/index"}
			format.xls 
		end
		
	end

	def show
	end

	def edit
	end

	def set_admin
		@user.update(admin: true)
		redirect_to users_path(admin: true)
	end

	def unset_admin
		@user.update(admin: false)
		redirect_to users_path()
	end

	def approved
		@user.update(approved: true)
		AdminMailer.user_approved(@user).deliver
		redirect_to users_path()
	end

	def disapproved
		@user.update(approved: false)
		redirect_to users_path(approved: false)
	end

	def approver
		@user.update(approver: true)
		redirect_to users_path()
	end

	def disapprover
		@user.update(approver: false)
		redirect_to users_path()
	end

	def public
		session[:public] = "user" if current_user.admin?
		redirect_to(:back)
	end

	def private
		session[:public] = "admin" if current_user.admin?
		redirect_to(:back)
	end

	def update
		respond_to do |format|
			if @user.update(user_params)
				format.html { redirect_to users_path, notice: 'User was successfully updated.' }
				format.json { render :show, status: :ok, location: @user }
			else
				format.html { render :edit }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@user.destroy
		respond_to do |format|
			format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private

	def is_admin?
		redirect_to root_path unless current_user.admin?
	end

	def set_user
		@user = User.find(params[:id])
	end

	def user_params
		registration_params = [:name, :email, :password, :password_confirmation, :approved, :master, :approver, :admin, :area, :address, :phone, :company, :cnpj, :work, :profile]
		params.require(:user).permit(registration_params)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, html: { role: "form", :class => "form-horizontal text-center"} do |f| %>
	<% if @user.errors.full_messages.any? %>
		<% @user.errors.full_messages.each do |error_message| %>
		<%= error_message if @user.errors.full_messages.first == error_message %> <br />
	<% end %>
	<% end %>
	
	<div class="form-group text-center">
		<%= f.label :nome, :class => "col-sm-4 control-label" %>
		<div class="col-sm-4">
			<%= f.text_field :name, autocomplete: "off", :class => "form-control" %>
		</div>
	</div>
	<div class="form-group text-center">
		<%= f.label :email, :class => "col-sm-4 control-label" %>
		<div class="col-sm-4">
			<%= f.email_field :email, autofocus: true, :class => "form-control" %>
		</div>
	</div>
	<div class="form-group text-center">
		<%= f.label :telefone, :class => "col-sm-4 control-label" %>
		<div class="col-sm-4">
			<%= f.text_field :phone, :class => "form-control" %>
		</div>
	</div>
	<div class="form-group text-center">
		<%= f.label :empresa, :class => "col-sm-4 control-label" %>
		<div class="col-sm-4">
			<%= f.text_field :company, :class => "form-control" %>
		</div>
	</div>
	<div class="form-group text-center">
		<%= f.label "CNPJ Empresa", :class => "col-sm-4 control-label" %>
		<div class="col-sm-4">
			<%= f.text_field :cnpj, :class => "form-control" %>
		</div>
	</div>
	<div class="form-group text-center">
		<%= f.label :departamento, :class => "col-sm-4 control-label" %>
		<div class="col-sm-4">
			<%= f.text_field :area, :class => "form-control" %>
		</div>
	</div>
	<div class="form-group text-center">
		<%= f.label :cargo, :class => "col-sm-4 control-label" %>
		<div class="col-sm-4">
			<%= f.text_field :work, :class => "form-control" %>
		</div>
	</div>
	<div class="form-group text-center">
		<%= f.label :perfil, :class => "col-sm-4 control-label" %>
		<div class="col-sm-4">
			<%= f.select(:profile, [['Funcionário Heinz', 1], ['Cliente', 2], ['Fornecedor', 3]], {}, {class: "form-control"}) %>
		</div>
	</div>
	<div class="form-group text-center">
		<%= f.submit 'Atualizar', :class => "btn btn-success" %>
		<%= link_to "Cancelar", "", :class => "btn btn-primary cancel" %>
	</div>
<% end %>

app/views/users/edit.html.erb
<div class="jumbotron">
	<div class="container">
		<h2>Editando <%= @user.name %> <small>ID do usuário:<%= @user.id %></small></h1>
	</div>
</div>
<div class="container">
	<%= render 'form' %>
	<div class="text-center">
		<%= button_to "Destruir", category_path(id: @user.id), method: :delete, data: { confirm: 'Tem certeza?' }, :class => "btn btn-danger" %>
	</div>
</div>

app/views/users/edit.js.erb
jQuery(".edit_form<%= @user.id %>").children().html("<%= escape_javascript(render(:partial => 'form')) %>");
jQuery(".edit_form<%= @user.id %>").fadeIn();

app/views/users/index.html.haml
.jumbotron{style: "padding: 20px;"}
	.container
		%ul.list-inline
			%li
				%h1
					Usuários
					%small #{@title}
			%li= button_to 'Download .XLS Usuários', users_path(format: "xls"), method: :get, :class => "btn btn-success btn-sm", style: "margin-left: 30px; margin-bottom: 20px"

		= link_to "Todos usuários", :action => "users_admin"
		|
		= link_to "Usuários esperando aprovação", :action => "users_admin", :approved => "false"
		|
		= link_to "Administradores", :action => "users_admin", :admin => "true"
.container
	%table{class: "table table-striped table-bordered table-condensed"}
		%thread
			%tr
				-if current_user.master == true
					%th.text-center Aprovador?
				%th.text-center Nome
				%th.text-center Email
				%th.text-center Aprovado?
				%th.text-center Admin?
				%th.text-center Ações
		- @users.each do |user|
			- unless User::STABLE.include?(user.email)
				%tr
					-if current_user.master == true
						%td.text-center
							- if user.approver
								= link_to "Remover Aprovador" , disapprover_path(id: user.id), method: :put, :class => "btn btn-default btn-sm"
							- else
								= link_to "Selecionar Aprovador" , approver_path(id: user.id), method: :put, :class => "btn btn-primary btn-sm"
					%td.text-center= user.name
					%td.text-center= user.email
					%td.text-center
						- if user.approved && user != current_user
							= link_to "Desaprovar" , disapproved_path(id: user.id), method: :put, :class => "btn btn-default btn-sm"
						- elsif !user.approved && user != current_user
							= link_to "Aprovar" , approved_path(id: user.id), method: :put, :class => "btn btn-primary btn-sm"
						- else
							= link_to "Desaprovar" , disapproved_path(id: user.id), method: :put, :class => "btn btn-default btn-sm", disabled: "disabled"
					%td.text-center
						- if user.admin && user != current_user
							=link_to "Remover" , unset_admin_path(id: user.id), method: :put, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-sm"
						- elsif !user.admin && user != current_user
							=link_to "Admin" , set_admin_path(id: user.id), method: :put, data: { confirm: 'Are you sure?' }, :class => "btn btn-default btn-sm"
						- else
							=link_to "Remover" , unset_admin_path(id: user.id), :class => "btn btn-danger btn-sm", disabled: "disabled"

					%td.text-center
						= link_to "Editar Usuário", edit_user_path(id: user.id), :class => "btn btn-primary btn-sm edit", remote: true
						= link_to "Deletar Usuário", user_path(id: user.id), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-sm"
				%tr{class: "edit_form#{user.id}", style: "display: none;"}
					%td.text-center{colspan: 6} a
			- else
				%tr
					-if current_user.master == true
						%td.text-center
							- if user.approver
								= link_to "Remover Aprovador" , disapprover_path(id: user.id), method: :put, :class => "btn btn-default btn-sm"
							- else
								= link_to "Selecionar Aprovador" , approver_path(id: user.id), method: :put, :class => "btn btn-primary btn-sm"
					%td.text-center= user.name
					%td.text-center= user.email
					%td.text-center
						= link_to "Desaprovar" , disapproved_path(id: user.id), method: :put, :class => "btn btn-default btn-sm", disabled: "disabled"
					%td.text-center
						=link_to "Remover" , unset_admin_path(id: user.id), :class => "btn btn-danger btn-sm", disabled: "disabled"

					%td.text-center
						= link_to "Editar Usuário", edit_user_path(id: user.id), :class => "btn btn-primary btn-sm edit", remote: true, disabled: "disabled"
						= link_to "Deletar Usuário", user_path(id: user.id), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-sm" , disabled: "disabled"

app/views/users/users_admin.xls.erb
<?xml version="1.0" encoding="UTF-8"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Styles>
    <Style ss:ID="value">
      <NumberFormat ss:Format="@"/>
    </Style>
  </Styles>
  <Worksheet ss:Name="Usuários">
    <Table>
      <ss:Column ss:Width="25" ss:AutoFitWidth="1"/>
      <ss:Column ss:Width="120" ss:AutoFitWidth="1"/>
      <ss:Column ss:Width="160" ss:AutoFitWidth="1"/>
      <ss:Column ss:Width="150" ss:AutoFitWidth="1"/>
      <ss:Column ss:Width="120" ss:AutoFitWidth="1"/>
      <ss:Column ss:Width="100" ss:AutoFitWidth="1"/>
      <ss:Column ss:Width="100" ss:AutoFitWidth="1"/>
      <ss:Column ss:Width="100" ss:AutoFitWidth="1"/>
      <ss:Column ss:Width="100" ss:AutoFitWidth="1"/>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Nome</Data></Cell>
        <Cell><Data ss:Type="String">Email</Data></Cell>
        <Cell><Data ss:Type="String">Empresa</Data></Cell>
        <Cell><Data ss:Type="String">CNPJ Empresa</Data></Cell>
        <Cell><Data ss:Type="String">Area</Data></Cell>
        <Cell><Data ss:Type="String">Cargo</Data></Cell>
        <Cell><Data ss:Type="String">Telefone</Data></Cell>
        <Cell><Data ss:Type="String">Perfil</Data></Cell>
      </Row>
    <% @users.each do |u| %>
      <Row>
        <Cell ss:StyleID="value"><Data ss:Type="String"><%= u.id %></Data></Cell>
        <Cell ss:StyleID="value"><Data ss:Type="String"><%= u.name %></Data></Cell>
        <Cell ss:StyleID="value"><Data ss:Type="String"><%= u.email %></Data></Cell>
        <Cell ss:StyleID="value"><Data ss:Type="String"><%= u.company %></Data></Cell>
        <Cell ss:StyleID="value"><Data ss:Type="String"><%= u.cnpj %></Data></Cell>
        <Cell ss:StyleID="value"><Data ss:Type="String"><%= u.area %></Data></Cell>
        <Cell ss:StyleID="value"><Data ss:Type="String"><%= u.work %></Data></Cell>
        <Cell ss:StyleID="value"><Data ss:Type="String"><%= u.phone %></Data></Cell>

        <Cell ss:StyleID="value"><Data ss:Type="String"><%= 
            case u.profile
              when "1" then "Funcionário Heinz"
              when "2" then "Cliente"
              when "3" then "Fornecedor"
            end
        %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>


<!-- <table border="1" style="font-size: 1em; width: 75%">
  <tr>
      <th>ID</th>
      <th>Nome</th>
      <th>Email</th>
      <th>Empresa</th>
      <th>CNPJ Empresa</th>
      <th>Area</th>
      <th>Cargo</th>
      <th>Telefone</th>
      <th>Perfil</th>
  </tr>
  <% @users.each do |u| %>
    <tr>
        <td> <%= u.id%> </td>
        <td> <%= u.name%> </td>
        <td> <%= u.email%> </td>
        <td> <%= u.company%> </td>
        <td> <%= u.cnpj%> </td>
        <td> <%= u.area%> </td>
        <td> <%= u.work%> </td>
        <td> <%= u.phone%> </td>
        <td><%= 
          case u.profile
          when "1" then "Funcionário Heinz"
          when "2" then "Cliente"
          when "3" then "Fornecedor"
          end
        %>
        </td>
    </tr>
  <% end %>
</table> -->