config/routes.rb
Rails.application.routes.draw do

devise_for :users
devise_scope :user do
	root :to => 'devise/sessions#new'
end

get 'images/control' => 'images#control', as: :images_control
get 'images/export' => 'images#export', as: :images_export
post 'images/import' => 'images#import', as: :images_import
get 'users' => 'users#users_admin', as: :users
put 'users/:id/approved' => 'users#approved', as: :approved
put 'users/:id/disapproved' => 'users#disapproved', as: :disapproved
put 'users/:id/approver' => 'users#approver', as: :approver
put 'users/:id/disapprover' => 'users#disapprover', as: :disapprover
put 'users/:id/set_admin' => 'users#set_admin', as: :set_admin
put 'users/:id/unset_admin' => 'users#unset_admin', as: :unset_admin
put 'users/public' => 'users#public', as: :public
put 'users/private' => 'users#private', as: :private
resources :users, only: [:show, :edit, :update, :destroy]

resources :categories, only: [:index, :new, :create] do
	post :search, on: :member
	resources :images do
		get :download, on: :member
	end
end
resources :categories, path: "", except: [:index, :new, :create]



  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/category.rb
class Category < ActiveRecord::Base
	extend FriendlyId
	belongs_to :parent, :class_name => "Category"
	has_many :children,  :class_name => "Category", :foreign_key => "parent_id"
	has_many :images

	validates :name, presence: true
  friendly_id :slug_candidates, use: :slugged
	scope :leafs, -> {Category.all.select {|c| c.is_leaf?}}

	STABLE = ["Heinz", "Quero"]

	def is_leaf?
		false
		true if self.children.empty?
	end

	def slug_candidates
		[
			:name,
			[:name, parent.id]
		]
	end

	def ancestors
		if self.parent
			return self.parent.ancestors << self
		else
			return [self]
		end
	end

	def children_id
		unless self.children.blank?
			list = []
			self.children.each do |c|
				list << c.children_id
			end
			return list.flatten! << self.id
		else
			return [self.id]
		end
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :set_category, only: [:show, :edit, :update, :destroy, :search]
	before_action :authenticate_user!
	before_action :is_admin?, only: [:edit, :update, :new, :destroy]
	caches_page :show, :new

	def root_page
	end

	def index
		if params[:category] == "Quero"
			@categories = Category.find_by_name("Quero").children
			@title = "quero"
		elsif params[:category] == "Heinz"
			@categories = Category.find_by_name("Heinz").children
			@title = "heinz"
		else
			@categories = Category.all.order("updated_at DESC")
			@title = "todas"
		end
		render "categories/public/index" unless session[:public] == "admin"
	end

	def show
		@images = @category.images
		unless session[:public] == "admin"
			if @category.is_leaf?
				render "categories/public/shutter"
			else
				render "categories/public/show"
			end
		end
	end

	def new
		@category = Category.new
		@parent = params[:id]
		@name = Category.find(params[:id]).name unless @parent.blank?
	end

	def edit
		@parent = params[:parent]
	end

	def create
		@category = Category.new(category_params)
		@category.height = @category.parent.height + 1 if @category.parent

		respond_to do |format|
			if @category.save
				format.html { redirect_to @category, notice: 'Category was successfully created.' }
				format.json { render :show, status: :created, location: @category }
			else
				format.html { render :new }
				format.json { render json: @category.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		respond_to do |format|
			if @category.update(category_params)
				format.html { redirect_to @category, notice: 'Category was successfully updated.' }
				format.json { render :show, status: :ok, location: @category }
			else
				format.html { render :edit }
				format.json { render json: @category.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@category.destroy
		respond_to do |format|
			format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	def search
		@heinzimages = Image.search(params[:query], Category.first.children_id)
		@queroimages = Image.search(params[:query], Category.second.children_id)
		@both = false
		if @heinzimages.count > 0 && @queroimages.count > 0
			@both = true
			render "categories/public/shutter"
		elsif @heinzimages.count > 0 && @queroimages.count == 0
			@category = Category.first
			@images = @heinzimages
			render "categories/public/shutter"
		elsif @heinzimages.count == 0 && @queroimages.count > 0
			@category = Category.second
			@images = @queroimages
			render "categories/public/shutter"
		else
			@errorh = "Nenhum resultado encontrado."
			@queryh = params[:query]
			render "categories/public/index"
		end
		

		# @images = Image.search(params[:query], @category.children_id)
		# @image = Image.find(@images[0].id) unless @images[0].nil?
		# redirect_to category_image_path(category_id: @image.category, id: @image) if @images.size == 1
		# render "categories/public/shutter" if @images.size > 1
		# if @images.size == 0
		# 	if @category.id == Category.find_by_name("Heinz").id
		# 		@errorh = "Nenhum resultado encontrado."
		# 		@queryh = params[:query]
		# 	else
		# 		@errorq = "Nenhum resultado encontrado."
		# 		@queryq = params[:query]
		# 	end
		# 	render "categories/public/index"
		# end
	end

	private

	def is_admin?
		redirect_to root_path unless current_user.admin?
	end

	def set_category
		@category = Category.friendly.find(params[:id])
	end

	def category_params
		params.require(:category).permit(:name, :parent_id, :height)
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
	  def nested_category_path(category)
    '/' + (category.ancestors).map(&:to_param).join('/')
  end
end

app/views/categories/_form.html.erb
<%= form_for @category, html: { role: "form", :class => "form-horizontal text-center"}  do |f| %>
	<% if @category.errors.full_messages.any? %>
		<% @category.errors.full_messages.each do |error_message| %>
		<%= error_message if @category.errors.full_messages.first == error_message %> <br />
	<% end %>
	<% end %>
	<div class="form-group text-center">
		<%= f.label :nome, :class => "col-sm-4 control-label" %>
		<div class="col-sm-4">
			<%= f.text_field :name, :class => "form-control" %>
	</div>
	</div>
	<div class="form-group text-center">
		<%= f.label :superior, :class => "col-sm-4 control-label" %>
		<div class="col-sm-4">
			<%= f.collection_select(:parent_id, Category.order(:id),:id, :name, {prompt: "Selecione categoria superior", selected: @parent}, {class: "form-control"}) %>
		</div>
	</div>
	<div class="form-group text-center">
		<%= f.submit 'Atualizar', :class => "btn btn-success" %>
		<% if @category.new_record? %>
			<% if @parent %>
				<%= link_to 'Voltar', nested_category_path(Category.find(@parent)),:class => "btn btn-warning" %>
			<% else %>
				<%= link_to 'Voltar', categories_path, :class => "btn btn-warning" %>
			<% end %>
		<% else %>
			<%= link_to "Cancelar", "", :class => "btn btn-primary cancel" %>
		<% end %>
	</div>
<% end %>

app/views/categories/edit.html.erb
<div class="jumbotron" style="padding: 20px;">
	<div class="container">
		<h1>Editando <%= @category.name %><br/>
		<small>Superior: <%= @category.parent ? @category.parent.name : "root" %></small></h1>
	</div>
</div>
<div class="container">
	<%= render 'form' %>
</div>

app/views/categories/edit.js.erb
jQuery(".edit_form<%= @category.id %>").children().html("<%= escape_javascript(render(:partial => 'form')) %>");
jQuery(".edit_form<%= @category.id %>").fadeIn();

app/views/categories/index.html.haml
.jumbotron{style: "padding: 15px;"}
	.container
		%ul.list-inline
			%li
				%h1
					Categorias
					%small #{@title}
			%li= button_to 'Nova Categoria', new_category_path, method: :get, :class => "btn btn-primary btn-sm", style: "margin-left: 30px; margin-bottom: 20px"
			%li= link_to 'Controle de Produtos', images_control_path(), method: :get, :class => "btn btn-success btn-sm", style: "margin-left: 30px; margin-bottom: 20px"
		= link_to "Todas Categorias", :action => "index"
		|
		= link_to "Categorias Heinz", :action => "index", :category => "Heinz"
		|
		= link_to "Categorias Quero", :action => "index", :category => "Quero"
.container
	%table{class: "table table-striped table-bordered table-condensed"}
		%thread
			%tr
				%th.text-center #
				%th.text-center Nome
				%th.text-center Superior
				%th.text-center Altura
				%th.text-center Ações
		- @categories.each do |cat|
			- unless (Category::STABLE.include?(cat.name))
				%tr
					%td.text-center= cat.id
					%td.text-center= link_to cat.name, cat, :class => "btn btn-link"
					%td.text-center= cat.parent ? cat.parent.name : "root"
					%td.text-center= cat.height
					%td.text-center
						= link_to "Editar", edit_category_path(id: cat.id, parent: cat.parent ? cat.parent.id : nil), :class => "btn btn-primary btn-sm edit" , remote: true
						= link_to "Destruir", category_path(id: cat.id), method: :delete, data: { confirm: 'Tem certeza?' }, :class => "btn btn-danger btn-sm"
				%tr{class: "edit_form#{cat.id}", style: "display: none;"}
					%td.text-center{colspan: 6} a
			- else
				%tr
					%td.text-center= cat.id
					%td.text-center= link_to cat.name, cat, :class => "btn btn-link"
					%td.text-center= cat.parent ? cat.parent.name : "root"
					%td.text-center= cat.height
					%td.text-center
						= link_to "Editar", edit_category_path(id: cat.id, parent: cat.parent ? cat.parent.id : nil), :class => "btn btn-primary btn-sm edit" , disabled:   "disabled"
						= link_to "Destruir", category_path(id: cat.id), method: :delete, data: { confirm: 'Tem certeza?' }, :class => "btn btn-danger btn-sm", disabled:   "disabled"

app/views/categories/new.html.erb
<div class="jumbotron" style="padding: 20px;">
	<div class="container">
		<h2>Categoria<br/><small class="note">Criando categoria dentro de: <%= @name ? @name : "root" %></small></h2>
	</div>
</div>

<div class="container">
	<%= render 'form' %>
</div>

app/views/categories/show.html.haml
.jumbotron{style: "padding: 20px;"}
	.container
		%ul.list-inline
			%li
				%h1
					= @category.name
					- if @category.parent
						%small - #{@category.parent.name}
				%li= link_to 'Nova Categoria', new_category_path(id: @category.id), method: :get, :class => "btn btn-primary btn-sm", style: "margin-left: 30px; margin-bottom: 20px;"
			- if @category.is_leaf?
				%li= link_to 'Nova Imagem', new_category_image_path(category_id: @category.slug), method: :get, :class => "btn btn-info btn-sm", style: "margin-bottom: 20px;"
.container
	.col-md-12.text-center
		.col-md-12.text-center
			- if @category.parent
				= button_to @category.parent.name, @category.parent, method: :get, class: "btn btn-default btn-sm", style: "margin-bottom: 10px;"
			- else
				= button_to "root", categories_path, method: :get, class: "btn btn-default btn-sm", style: "margin-bottom: 10px;"
		.col-md-12.text-center
			%p{style: "color: #d3d3d3"} \/
		.col-md-12.text-center{style: "margin-bottom: 10px;"}
			= link_to @category.name, @category, method: :get, class: "btn btn-default btn-sm", disabled: "disabled"
			%p{style: "position: absolute; right: 40%;color: #d3d3d3; bottom: -4px;"} ->
			- unless @category.images.empty?
				= link_to "Todos Produtos", category_images_path(@category),:class => "btn btn-success btn-sm", style: "position: absolute; right: 25%; display: inline;"
		.col-md-12.text-center
			%p{style: "color: #d3d3d3"} \/
		.col-md-12.text-center
			%ul.list-inline
				- @category.children.each do |cat|
					%li= button_to cat.name, cat, method: :get, class: "btn btn-default btn-sm", style: "margin-top: 10px;"
				- @images.each do |img|
					%li= button_to img.name, category_image_path(@category, img), method: :get, class: "btn btn-success btn-sm", style: "margin-top: 10px;"
		.col-md-12.text-center{style: "margin-top: 20px; margin-bottom: 10px;"}
			- unless Category::STABLE.include?(@category.name)
				= link_to "Destruir", category_path(id: @category), method: :delete, data: { confirm: 'tem certeza?' }, :class => "btn btn-danger"
				- if @category.parent
					= link_to 'Voltar', nested_category_path(Category.find(@category.parent)),:class => "btn btn-warning"
				- else
					= link_to 'Voltar', categories_path, :class => "btn btn-warning"
			- else
				= link_to "Destruir", category_path(id: @category), method: :delete, data: { confirm: 'tem certeza?' }, :class => "btn btn-danger", disabled: "disabled"
				- if @category.parent
					= link_to 'Voltar', nested_category_path(Category.find(@category.parent)),:class => "btn btn-warning"
				- else
					= link_to 'Voltar', categories_path, :class => "btn btn-warning"