config/routes.rb
Rails.application.routes.draw do

devise_for :users
devise_scope :user do
	root :to => 'devise/sessions#new'
end

get 'images/control' => 'images#control', as: :images_control
get 'images/export' => 'images#export', as: :images_export
post 'images/import' => 'images#import', as: :images_import
get 'users' => 'users#users_admin', as: :users
put 'users/:id/approved' => 'users#approved', as: :approved
put 'users/:id/disapproved' => 'users#disapproved', as: :disapproved
put 'users/:id/approver' => 'users#approver', as: :approver
put 'users/:id/disapprover' => 'users#disapprover', as: :disapprover
put 'users/:id/set_admin' => 'users#set_admin', as: :set_admin
put 'users/:id/unset_admin' => 'users#unset_admin', as: :unset_admin
put 'users/public' => 'users#public', as: :public
put 'users/private' => 'users#private', as: :private
resources :users, only: [:show, :edit, :update, :destroy]

resources :categories, only: [:index, :new, :create] do
	post :search, on: :member
	resources :images do
		get :download, on: :member
	end
end
resources :categories, path: "", except: [:index, :new, :create]



  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "1000x", small: "500x" , show: "x400", thumb: "x200" }
  belongs_to :category
	validates :name,  presence: true
	# validates :avatar, presence: true


  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (3..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      product = Image.find_by_id(row["id"])
      product.update_attributes(row.to_hash)
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Roo::Csv.new(file.path, nil, :ignore)
    when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end

  def self.search(query, cat_children)
    if query.present?
      if query.is_number?
        return where("code = :c", c: query).where("category_id IN (?)", cat_children)
      else
        where("name @@ :q", q: query).where("category_id IN (?)", cat_children)
      end
    end
  end

  def save_image_size
    unless @size_saved
      self.original_size = Paperclip.io_adapters.for(avatar(:original)).size
      self.medium_size = Paperclip.io_adapters.for(avatar(:medium)).size
      self.small_size = Paperclip.io_adapters.for(avatar(:small)).size
      @size_saved = true
      self.save
    end
  end

  def save_geometry
    unless @geometry_saved
      self.original_geometry = get_geometry(:original)
      self.medium_geometry = get_geometry(:medium)
      self.small_geometry = get_geometry(:small)
      @geometry_saved = true
      self.save
    end
  end

  def get_geometry(style = :original)
    begin
      Paperclip::Geometry.from_file(avatar.url(style)).to_s
    rescue
      nil
    end
  end
end
class String
  def is_number?
    true if Float(self) rescue false
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	before_action :set_image, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!

  caches_page :index, :show, :new, :edit

  def index
    @category = Category.friendly.find(params[:category_id])
    @images = @category.images
  end

	def new
		@image = Image.new
		@category = Category.friendly.find(params[:category_id])
		@name = Category.friendly.find(@category.id).name unless @category.nil?
	end

	def show
		 @category = Category.friendly.find(params[:category_id])
		render "images/public/show" unless session[:public] == "admin"
	end

  def create
  	@category = Category.friendly.find(params[:category_id])
    @image = Image.new(image_params)
    if @image.save
      redirect_to @image.category, notice: 'Image was successfully created.'
     else
       render action: 'new'
    end
  end

  def edit
    @category = @image.category
  end

  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to category_image_path(id: @image, category_id: @image.category), notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  	@category = @image.category
    @image.destroy
    respond_to do |format|
      format.html { redirect_to @category, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def download
		@image = Image.find(params[:id])
		style = params[:quality].to_sym
		ending = "_hd"
		ending = "_md" if style == :medium
		ending = "_sd" if style == :small

		send_file(Paperclip.io_adapters.for(@image.avatar(style)).path,
			:type => @image.avatar_content_type,
			:disposition => "attachment",
			:filename => @image.name+ending)
	end

  def export
    @images = Image.all.order(:code)
    respond_to do |format|
      format.xls 
    end
  end

  def import
    Image.import(params[:file])
    redirect_to images_control_url, notice: "Produtos importados corretamente."
  end

  def control
  end

  private
    def set_image
      @image = Image.find(params[:id])
    end
  def image_params
    params.require(:image).permit(:avatar, :name, :category_id, :code, :upc, :dim_unit, :weight_unit, :box_unit, :dim_box, :weight_box, :box_pallet, :description)
  end
end

app/views/images/_form.html.erb
<%= form_for [@category, @image] , :html => { :multipart => true, role: "form", :class => "form-horizontal text-center" } do |f| %>
	<% if @image.errors.full_messages.any? %>
		<% @image.errors.full_messages.each do |error_message| %>
		<%= error_message if @image.errors.full_messages.first == error_message %> <br />
	<% end %>
	<% end %>
	<div class="form-group text-center">
		<%= f.label :nome, :class => "col-sm-4 control-label" %>
		<div class="col-sm-4">
			<%= f.text_field :name, :class => "form-control" %>
		</div>
	</div>
	<div class="form-group text-center">
		<%= f.label :categoria, :class => "col-sm-4 control-label" %>
		<div class="col-sm-4">
			<%= f.collection_select(:category_id, Category.leafs,:id, :name, {prompt: "Select a category", selected: @category.id}, {class: "form-control"}) %>
		</div>
	</div>
	<div class="form-group text-center">
		<%= f.label :imagem, :class => "col-sm-4 control-label" %>
		<div class="col-sm-4">
			<%= f.file_field :avatar, :class => "form-control" %>
		</div>
	</div>
	<div class="form-group text-center">
		<%= f.label :código_de_produto, :class => "col-sm-4 control-label" %>
		<div class="col-sm-4">
			<%= f.text_field :code, :class => "form-control" %>
		</div>
	</div>
	<div class="form-group text-center">
		<%= f.label "UPC code", :class => "col-sm-4 control-label" %>
		<div class="col-sm-4">
			<%= f.text_field :upc, :class => "form-control" %>
		</div>
	</div>
	<div class="form-group text-center">
		<%= f.label :dimensões_da_unidade, :class => "col-sm-4 control-label" %>
		<div class="col-sm-4">
			<%= f.text_field :dim_unit, :class => "form-control" %>
		</div>
	</div>
	<div class="form-group text-center">
		<%= f.label :peso_da_unidade, :class => "col-sm-4 control-label" %>
		<div class="col-sm-4">
			<%= f.text_field :weight_unit, :class => "form-control" %>
		</div>
	</div>
	<div class="form-group text-center">
		<%= f.label :unidades_por_caixa, :class => "col-sm-4 control-label" %>
		<div class="col-sm-4">
			<%= f.text_field :box_unit, :class => "form-control" %>
		</div>
	</div>
	<div class="form-group text-center">
		<%= f.label :dimensões_da_caixa, :class => "col-sm-4 control-label" %>
		<div class="col-sm-4">
			<%= f.text_field :dim_box, :class => "form-control" %>
		</div>
	</div>
	<div class="form-group text-center">
		<%= f.label :peso_da_caixa, :class => "col-sm-4 control-label" %>
		<div class="col-sm-4">
			<%= f.text_field :weight_box, :class => "form-control" %>
		</div>
	</div>
	<div class="form-group text-center">
		<%= f.label :caixas_por_pallet, :class => "col-sm-4 control-label" %>
		<div class="col-sm-4">
			<%= f.text_field :box_pallet, :class => "form-control" %>
		</div>
	</div>
	<div class="form-group text-center">
		<%= f.label :descrição_produto, :class => "col-sm-4 control-label" %>
		<div class="col-sm-4">
			<%= f.text_area :description, :class => "form-control" %>
		</div>
	</div>
	<div class="form-group text-center">
		<%= f.submit 'Atualizar', :class => "btn btn-success" %>
		<% unless @category.nil? %>
			<%= link_to 'Voltar', category_images_path(@category),:class => "btn btn-warning" %>
		<% end %>
	</div>
<% end %>

app/views/images/_info.html.erb
<div>
	<h2>Informações do produto.</h1>
</div>
<div style="margin-top: 20px;">
	<p style="line-height: 1.6; text-align: center; margin: auto;">
	Nome: <b><%= @image.name %></b> <br />
	Código de Produto: <b><%= @image.code %></b><br />
	UPC Code: <b><%= @image.upc %></b><br />
	Dimensões da unidade: <b><%= @image.dim_unit %></b><br />
	Peso da unidade: <b><%= @image.weight_unit %></b><br />
	Unidades por caixa: <b><%= @image.box_unit %></b><br />
	Dimensões da caixa: <b><%= @image.dim_box %></b><br />
	Peso da caixa: <b><%= @image.weight_box %></b><br />
	Caixas pro pallet: <b><%= @image.box_pallet %></b><br />
	Descrição do produto: <b><%= @image.description %></b><br />

	</p>
</div>

app/views/images/control.html.haml
.jumbotron{style: "padding: 20px;"}
	.container
		%ul.list-inline
			%li
				%h1{style: "font-size: 3.4em"} 
					Controle de produtos<br />
					%small Exportação e Importação.
			%li= button_to 'Download .XLS Produtos', images_export_path(format: "xls"), method: :get, :class => "btn btn-success btn-sm", style: "margin-left: 30px; margin-bottom: 20px"
			%li= link_to 'Voltar', root_path, :class => "btn btn-warning btn-sm", style: "margin-bottom: 20px;"
.container
	.jumbotron.text-center{style: "padding: 10px;"}
		.h4 
			Regras<br />
			%small Edição correta do arquivo .xls
		%p{style: "font-size: 1.1em; line-height: 1.7em;"} 
			%i 1- 
			Os campos da coluna
			%b ID
			não devem ser alterados.<br />
			%i 2- 
			As 
			%b duas 
			primeiras linhas da planilhas
			%b não
			devem ser modificadas. Ambas contêm conteúdo lógico para a leitura feita pela aplicação.<br />
			%i 3- 
			Os campos 
			%b Código
			e 
			%b UPC Code
			podem conter apenas
			%u numerais. 
			Já os demais aceitam
			%b quaisquer
			caracteres.<br />
			%i 4-
			A 
			%b adição
			de novas linhas 
			%b não
			incluí novos produtos nos sistema. O produto (e sua imagem respectiva) devem ser adicionados pela aplicação. <br />
			%i 5-
			O arquivo a ser 
			%u importado
			deve estar no formato
			%b .xls
			padrão Excel 97-2014.
			

	#notice.text-center{style: "margin-bottom: 20px; color: green;"}
		= notice
	= form_tag images_import_path, multipart: true, role: "form", :class => "form-horizontal text-center" do
		.form-group.text-center
			= label_tag 'Arquivo .xls', nil, class: 'col-sm-4 control-label'
			.col-sm-4
				= file_field_tag :file, :class => "form-control"
		.form-group.text-center
			= submit_tag "Importar", :class => "btn btn-default"

app/views/images/edit.html.erb
<div class="jumbotron" style="padding: 20px;">
	<div class="container"> 
		<h1><%=@image.name%><br/><small class="note"> Categoria: <%= @category ? @category.name : "root"  %></small></h1>
	</div>
</div>

<div class="container">
	<%= render 'form' %>
</div>

app/views/images/export.xls.erb
<?xml version="1.0" encoding="UTF-8"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Styles>
    <Style ss:ID="blank">
      <Font ss:Color="#FFFFFF" />
    </Style>
    <Style ss:ID="value">
      <NumberFormat ss:Format="@"/>
    </Style>
  </Styles>
  <Worksheet ss:Name="Export">
    <Table>
      <ss:Column ss:Width="25" ss:AutoFitWidth="1"/>
      <ss:Column ss:Width="150" ss:AutoFitWidth="1"/>
      <ss:Column ss:Width="60" ss:AutoFitWidth="1"/>
      <ss:Column ss:Width="120" ss:AutoFitWidth="1"/>
      <ss:Column ss:Width="120" ss:AutoFitWidth="1"/>
      <ss:Column ss:Width="100" ss:AutoFitWidth="1"/>
      <ss:Column ss:Width="100" ss:AutoFitWidth="1"/>
      <ss:Column ss:Width="100" ss:AutoFitWidth="1"/>
      <ss:Column ss:Width="100" ss:AutoFitWidth="1"/>
      <ss:Column ss:Width="100" ss:AutoFitWidth="1"/>
      <ss:Column ss:Width="100" ss:AutoFitWidth="1"/>
      <Row>
        <Cell ss:StyleID="blank"><Data ss:Type="String">id</Data></Cell>
        <Cell ss:StyleID="blank"><Data ss:Type="String">name</Data></Cell>
        <Cell ss:StyleID="blank"><Data ss:Type="String">code</Data></Cell>
        <Cell ss:StyleID="blank"><Data ss:Type="String">upc</Data></Cell>
        <Cell ss:StyleID="blank"><Data ss:Type="String">dim_unit</Data></Cell>
        <Cell ss:StyleID="blank"><Data ss:Type="String">weight_unit</Data></Cell>
        <Cell ss:StyleID="blank"><Data ss:Type="String">box_unit</Data></Cell>
        <Cell ss:StyleID="blank"><Data ss:Type="String">dim_box</Data></Cell>
        <Cell ss:StyleID="blank"><Data ss:Type="String">weight_box</Data></Cell>
        <Cell ss:StyleID="blank"><Data ss:Type="String">box_pallet</Data></Cell>
        <Cell ss:StyleID="blank"><Data ss:Type="String">description</Data></Cell>
      </Row>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Nome</Data></Cell>
        <Cell><Data ss:Type="String">Código</Data></Cell>
        <Cell><Data ss:Type="String">UPC Code</Data></Cell>
        <Cell><Data ss:Type="String">Dimensões Unidade</Data></Cell>
        <Cell><Data ss:Type="String">Peso Unidade</Data></Cell>
        <Cell><Data ss:Type="String">Unidades por Caixa</Data></Cell>
        <Cell><Data ss:Type="String">Dmensões Caixa</Data></Cell>
        <Cell><Data ss:Type="String">Peso Caixa</Data></Cell>
        <Cell><Data ss:Type="String">Caixas por Pallet</Data></Cell>
        <Cell><Data ss:Type="String">Descrição</Data></Cell>
      </Row>
    <% @images.each do |u| %>
      <Row>
        <Cell ss:StyleID="value"><Data ss:Type="String"><%= u.id %></Data></Cell>
        <Cell ss:StyleID="value"><Data ss:Type="String"><%= u.name %></Data></Cell>
        <Cell ss:StyleID="value"><Data ss:Type="String"><%= u.code %></Data></Cell>
        <Cell ss:StyleID="value"><Data ss:Type="String"><%= u.upc %></Data></Cell>
        <Cell ss:StyleID="value"><Data ss:Type="String"><%= u.dim_unit %></Data></Cell>
        <Cell ss:StyleID="value"><Data ss:Type="String"><%= u.weight_unit %></Data></Cell>
        <Cell ss:StyleID="value"><Data ss:Type="String"><%= u.box_unit %></Data></Cell>
        <Cell ss:StyleID="value"><Data ss:Type="String"><%= u.dim_box %></Data></Cell>
        <Cell ss:StyleID="value"><Data ss:Type="String"><%= u.weight_box %></Data></Cell>
        <Cell ss:StyleID="value"><Data ss:Type="String"><%= u.box_pallet %></Data></Cell>
        <Cell ss:StyleID="value"><Data ss:Type="String"><%= u.description %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/images/index.html.haml
.jumbotron{style: "padding: 20px;"}
	.container
		%ul.list-inline
			%li
				%h1 
					#{@category.name}
					%small Imagens
			%li= link_to 'Nova Imagem', new_category_image_path(category_id: @category.slug), method: :get, :class => "btn btn-info btn-sm", style: "margin-bottom: 20px;"
			%li= link_to 'Voltar', category_path(@category), :class => "btn btn-warning btn-sm", style: "margin-bottom: 20px;"
.container
	%table{class: "table table-striped table-bordered table-condensed"}
		%thread
			%tr
				%th.text-center #
				%th.text-center Name
				%th.text-center Image
				%th.text-center Actions 
		- @images.each do |img|
			%tr
				%td{:style=>"vertical-align: middle;", :class=>"text-center"}= img.id 
				%td{:style=>"vertical-align: middle;", :class=>"text-center"}= img.name
				%td{:style=>"vertical-align: middle;", :class=>"text-center"}= link_to image_tag(img.avatar.url(:thumb)), category_image_path(@category.id, img.id)
				%td{:style=>"vertical-align: middle;", :class=>"text-center"}
					= link_to "Editar", edit_category_image_path(id: img.id), :class => "btn btn-primary btn-sm edit"
					= link_to "Destruir", category_image_path(@category.id, img.id), method: :delete, data: { confirm: 'Tem certeza?' }, :class => "btn btn-danger btn-sm"

app/views/images/new.html.erb
<div class="jumbotron" style="padding: 20px;">
	<div class="container"> 
		<h1>Nova Imagem<br/><small class="note"> Categoria: <%= @name ? @name : "root"  %></small></h1>
	</div>
</div>

<div class="container">
	<%= render 'form' %>
</div>

app/views/images/show.html.haml
.jumbotron{style: "padding: 20px;"}
	.container
		%ul.list-inline
			%li
				%h1
					= @image.name
					%small #{@category.name}
.container
	.col-md-12.text-center
		.col-md-6.text-center
			= image_tag @image.avatar.url(:show), style: "border: 1px solid gray"
		.col-md-6.text-center
			= render 'info'
		.col-md-12.text-center{style: "margin-top: 50px; margin-bottom: 10px;"}
			= link_to "Download", download_category_image_path(id: @image.id) , method: :get, :class => "btn btn-success"
			= link_to "Editar", edit_category_image_path(id: @image.id), :class => "btn btn-primary edit"
			= link_to "Destruir", category_image_path(@category, @image), method: :delete, data: { confirm: 'Tem certeza?' }, :class => "btn btn-danger"
			= link_to 'Voltar', "javascript:history.back()", :class => "btn btn-warning"