config/routes.rb
Rails.application.routes.draw do

devise_for :users
devise_scope :user do
	root :to => 'devise/sessions#new'
end

get 'images/control' => 'images#control', as: :images_control
get 'images/export' => 'images#export', as: :images_export
post 'images/import' => 'images#import', as: :images_import
get 'users' => 'users#users_admin', as: :users
put 'users/:id/approved' => 'users#approved', as: :approved
put 'users/:id/disapproved' => 'users#disapproved', as: :disapproved
put 'users/:id/approver' => 'users#approver', as: :approver
put 'users/:id/disapprover' => 'users#disapprover', as: :disapprover
put 'users/:id/set_admin' => 'users#set_admin', as: :set_admin
put 'users/:id/unset_admin' => 'users#unset_admin', as: :unset_admin
put 'users/public' => 'users#public', as: :public
put 'users/private' => 'users#private', as: :private
resources :users, only: [:show, :edit, :update, :destroy]

resources :categories, only: [:index, :new, :create] do
	post :search, on: :member
	resources :images do
		get :download, on: :member
	end
end
resources :categories, path: "", except: [:index, :new, :create]



  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Heinz - DigitalAssets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8"> 
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
</head>
<body style="padding-top: 50px;">
  <div id="preloader">
    <%= image_tag "heinz_header.png" %>
    <%= image_tag "quero_header.png" %>
    <%= image_tag "category.png" %>
  </div>
	<% if user_signed_in? %>
		<div class="navbar navbar-inverse navbar-fixed-top " role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<% if current_user.admin? %>
						<a class="navbar-brand" href="#"style="color: #d3d3d3;">Painel Admin</a>
					<% else %>
            <%= link_to image_tag("heinz_header.png", width: "55px;"), root_path, :class => "navbar-brand", style:"color: #d3d3d3" %>
					<% end %>
				</div>
				<div class="collapse navbar-collapse">
					<% if current_user.admin? %>
						<ul class="nav navbar-nav">
							<li class="<%=is_active('users')%>"><%= link_to "Usuários", users_path, style:"color: #d3d3d3;" %></li>
							<li class="<%=is_active('categories')%>"><%= link_to "Categorias", categories_path, style:"color: #d3d3d3;" %></li>
							<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <% if session[:public] == "admin" %>
                  <b style="color: #c6c6c6;">Admin </b><span class="caret"></span></a>
                <% else %>
                  <b style="color: #c6c6c6;">Usuário </b><span class="caret"></span></a>
                <% end %>
								<ul class="dropdown-menu" role="menu">
									  <li><%= link_to "Administrador", private_path, method: :put %></li>
									  <li><%= link_to "Usuário", public_path, method: :put %></li>
								</ul>
							</li>
						</ul>
					<% end %>
					<ul class="nav navbar-nav navbar-right">
						<li class="navbar-text" style="color: #d3d3d3;">Olá <strong><%= current_user.name %></strong>!</li>
						<li><%= button_to 'Editar perfil', edit_user_registration_path, method: :get, :class => 'btn btn-primary navbar-btn btn-sm', style: "margin-right: 6px;"%></li>
						<li><%= button_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-danger navbar-btn btn-sm'  %></li>
					</ul>
				</div><!--/.nav-collapse -->
			</div>
		</div>
	<% end %>
	<%= yield %>
  <% if session[:public] == "admin" %>
    <footer class="container text-center">
      <p>&copy; Heinz Brasil 2014 <br/>
        Agência Lado9 - <a href="http://lado9.com.br">lado9.com.br</a></p>
    </footer>
  <% end %>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
<title>HeinzDigitalAssets</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<meta name="viewport" content="initial-scale=1, maximum-scale=1">
<style>

body {
	background: #fefefd; /* Old browsers */
	background: -moz-linear-gradient(left, #fefefd 0%, #ebe8c3 50%, #fefefd 100%); /* FF3.6+ */
	background: -webkit-gradient(linear, left top, right top, color-stop(0%,#fefefd), color-stop(50%,#ebe8c3), color-stop(100%,#fefefd)); /* Chrome,Safari4+ */
	background: -webkit-linear-gradient(left, #fefefd 0%,#ebe8c3 50%,#fefefd 100%); /* Chrome10+,Safari5.1+ */
	background: -o-linear-gradient(left, #fefefd 0%,#ebe8c3 50%,#fefefd 100%); /* Opera 11.10+ */
	background: -ms-linear-gradient(left, #fefefd 0%,#ebe8c3 50%,#fefefd 100%); /* IE10+ */
	background: linear-gradient(to right, #fefefd 0%,#ebe8c3 50%,#fefefd 100%); /* W3C */
	filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#fefefd', endColorstr='#fefefd',GradientType=1 ); /* IE6-9 */
	min-height: 300px;
	max-height: 500px;
	height: 100%;
	width: 100%;
}
 </style>
</head>
<body>
	<div id="preloader">
		<%= image_tag "heinz_header.png" %>
	</div>
	<%= yield %>
	<% if session[:public] == "admin" %>
		<footer class="container text-center"><p>&copy; Heinz Brasil 2014</p> </footer>
	<% end %>
</body>
</html>